--- 
after_success: 
  - "mvn clean cobertura:cobertura coveralls:cobertura"
before_deploy: 
  - "mvn help:evaluate -N -Dexpression=project.version|grep -v '\\['"
  - "export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\\[')"
  - "export TRAVIS_TAG=$project_version"
cache: 
  directories: 
    - ~/.m2/repository
deploy: 
  api_key: 
    secure: bHTo3rdrHyB6cpbOU2wRKKkePHbfkkzH4o9pQ4fi/M7uurWzQoBjIkZ8Z46chjyqt0Gwse9hy8Vum6cnDCjmWo4E3bW4sGdjnnxnF+voG0BKVI8kodKuXTbCyUv0eC0fUIUEYITt95LJqeq3jxFMjKkPEQRpvtgJhDOV02ST9xk=
  file: 
    - sentilo-*/target/sentilo-*-$project_version.jar
    - sentilo-platform/sentilo-*/target/sentilo-*-$project_version.jar
  file_glob: true
  name: $project_version
  overwrite: true
  provider: releases
  skip_cleanup: true
  true: 
    repo: sentilo/sentilo
jdk: 
  - oraclejdk8
language: java
sudo: false
