sudo: false
language: java
jdk:
- oraclejdk8

after_success:
- mvn clean cobertura:cobertura coveralls:cobertura

## Get the project version
before_deploy:
    - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
    - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
	- export TRAVIS_TAG=$project_version
	

## Create release in GitHub 
deploy:
  provider: releases
  api_key:
    secure: bHTo3rdrHyB6cpbOU2wRKKkePHbfkkzH4o9pQ4fi/M7uurWzQoBjIkZ8Z46chjyqt0Gwse9hy8Vum6cnDCjmWo4E3bW4sGdjnnxnF+voG0BKVI8kodKuXTbCyUv0eC0fUIUEYITt95LJqeq3jxFMjKkPEQRpvtgJhDOV02ST9xk=
  file_glob: true
  file: 
    - sentilo-*/target/sentilo-*-$project_version.jar
	- sentilo-platform/sentilo-*/target/sentilo-*-$project_version.jar  
  skip_cleanup: true
  on:    
    repo: sentilo/sentilo
  name: $project_version
  overwrite: true  

  
cache:
    directories:
        - ~/.m2/repository  